#!/bin/bash

git_author_stats() {
  git -C $1 log --author="$2" --since=$3  --until=$4 --numstat --pretty="%ae %H" \
    | grep -v -E '.*\.(svg)$' \
    | sed 's/@.*//g' \
    | awk '{ if (NF == 1){ name = $1}; if(NF == 3) {plus[name] += $1; minus[name] += $2}} END { for (name in plus) {print name": "plus[name]" "minus[name]}}' \
    | sort -k2 -gr
}

if [ $# -lt 2 ]; then
  echo "Invalid arguments. Usage: ./cloc-author-date '<since-date>' 'author(s)' '<optional-until-date>'"
  exit 1
fi

if [ ! -f ./repos.txt ]; then
    echo "Missing 'repos.txt' file with a list of repositories. Refer to the README.md for more information."
    exit 1
fi

SINCE=$1
USERS=$2
UNTIL=${3:-$(date)}
REPOS=$(cat "repos.txt")

# Optionally comment out the line below if you are doing multiple reports with a recent git clone in .cloc-tmp
rm -rf .cloc-tmp
rm -rf reports
mkdir reports

echo "Counting lines of code between $SINCE -> $UNTIL"
for REPO in $REPOS
do
    echo "Pull down $REPO repo 📁"
    DIR="./.cloc-tmp/$REPO"
    # Optionally comment out the line below if you are doing multiple reports with a recent git clone in .cloc-tmp
    git clone "$REPO" $DIR
    for USER in $USERS
    do
        echo "Generating report for $USER 📄"
        git_author_stats $DIR $USER $SINCE $UNTIL >> ./reports/$USER.txt
    done
done

echo "\nCloc Totals 📊"
echo "\n📒 Emails with no commits found will be excluded from results"
echo "----------------------------------------------------------------\n"

# Print line totals for each developer
for FILE in ./reports/*.txt
do
    awk '{for(i=2;i<=NF;i++)$i=(a[i]+=$i)}END{if (length($1) != 0) {print $1" +"$2" -"$3}}' $FILE >> ./reports/summary-report.txt
done
cat ./reports/summary-report.txt

# Print team total and delta
awk 'BEGIN{FS=" "; sumPlus=0; sumMinus=0} {sumPlus+=$2; sumMinus+=$3;} END{print "\nTeam Total: +"sumPlus " "sumMinus" \nDelta: " sumPlus + sumMinus}' ./reports/summary-report.txt

# Optionally comment out the line below if you are doing multiple reports with a recent git clone in .cloc-tmpO
rm -rf .cloc-tmp
